name: sutil
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.18.0
  logger: ^2.0.2+1
  path_provider: ^2.0.14
  path: ^1.8.2
  uuid: ^4.2.1
  encrypt: ^5.0.3
  pointycastle: '>=3.0.0 <=4.0.0'
  dio: ">=5.4.1 <6.0.0"
  connectivity_plus: ^5.0.2
  injectable: ^2.3.3
  event_ship:
    git:
      url: https://github.com/ENUUI/event_ship.git
      ref: v1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0